import { api } from "./api";

export const getUserProfile = async () => (await api.get("/api/me")).user;
export const saveUserProfile = (_userId, values) => api.patch("/api/me", values);
export const getUserTransactions = () => api.get("/api/transactions");
export const getAllTransactions = () => api.get("/api/admin/transactions");
export const createTransaction = (values) => api.post("/api/transactions", values);
export const updateTransaction = (transactionId, values) => api.patch(`/api/transactions/${transactionId}`, values);
export const getAllUsers = () => api.get("/api/admin/users");
export const getCategories = () => api.get("/api/categories");
export const createCategory = (values) => api.post("/api/admin/categories", values);
export const removeCategory = (categoryId) => api.delete(`/api/admin/categories/${categoryId}`);
export const createNotification = (values) => api.post("/api/admin/notifications", values);
export const getUserNotifications = () => api.get("/api/notifications");
export const getPaymentMethods = () => api.get("/api/payment-methods");
export const createPaymentMethod = (values) => api.post("/api/admin/payment-methods", values);
export const removePaymentMethod = (methodId) => api.delete(`/api/admin/payment-methods/${methodId}`);
export const getPaymentRequests = (userId) => api.get(userId ? "/api/payment-requests" : "/api/admin/payment-requests");
export const createPaymentRequest = (values) => api.post("/api/payment-requests", values);
export const updatePaymentRequest = (requestId, values) => api.patch(`/api/admin/payment-requests/${requestId}`, values);
export const saveUserEntitlement = (userId, values) => api.patch(`/api/admin/users/${userId}/entitlement`, values);
export const uploadPaymentReceipt = async (_userId, file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); });
