import React, { useEffect, useState } from "react";
import { Button, Input, message } from "antd";
import { ArrowLeftOutlined, CheckOutlined, DeleteOutlined, PlusOutlined, CloseOutlined } from "@ant-design/icons";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { createNotification, createPaymentMethod, getPaymentMethods, getPaymentRequests, removePaymentMethod, updatePaymentRequest } from "../services/firestore";

const AdminPayments = () => {
  const { user } = useAuth();
  const [methods, setMethods] = useState([]);
  const [requests, setRequests] = useState([]);
  const [form, setForm] = useState({ bankName: "", cardNumber: "", holderName: "", price: "" });
  const [busy, setBusy] = useState(false);
  const reload = () => Promise.all([getPaymentMethods(), getPaymentRequests()]).then(([cards, payments]) => { setMethods(cards); setRequests(payments); });
  useEffect(() => { reload().catch(() => message.error("Payment ma'lumotlarini yuklab bo'lmadi")); }, []);
  const addCard = async (event) => { event.preventDefault(); if (!form.cardNumber.trim()) return message.warning("Karta raqamini kiriting"); setBusy(true); try { await createPaymentMethod({ ...form, createdAt: new Date().toISOString(), active: true }); setForm({ bankName: "", cardNumber: "", holderName: "", price: "" }); await reload(); message.success("Karta qo'shildi"); } catch { message.error("Karta saqlanmadi"); } finally { setBusy(false); } };
  const decide = async (payment, status) => { try { await updatePaymentRequest(payment.id, { status, reviewedAt: new Date().toISOString(), reviewedBy: user.id }); if (status === "approved") await createNotification({ audience: payment.userId, title: "Pro tarif faollashdi", body: "Tabriklaymiz! Siz Moliyam Pro tarifiga o'tdingiz.", createdAt: new Date().toISOString(), status: "queued" }); else await createNotification({ audience: payment.userId, title: "To'lov bekor qilindi", body: "To'lovingiz tasdiqlanmadi. Iltimos, chek rasmini tekshirib qayta yuboring.", createdAt: new Date().toISOString(), status: "queued" }); await reload(); message.success(status === "approved" ? "Pro tasdiqlandi" : "To'lov bekor qilindi"); } catch { message.error("Amalni bajarib bo'lmadi"); } };
  if (!user || (user.role !== "admin" && user.isAdmin !== true)) return null;
  return <section className="admin-payments-page"><Link to="/admin" className="payment-back"><ArrowLeftOutlined /> Admin panelga qaytish</Link><div className="admin-payment-header"><div><p className="admin-kicker">Moliyam Pro</p><h1>To'lovlar boshqaruvi</h1><p>Karta raqamlari va foydalanuvchi cheklarini boshqaring.</p></div></div><div className="admin-payment-grid"><div className="admin-surface"><div className="admin-surface-head"><div><span className="admin-kicker">Qabul qilish</span><h2>To'lov kartalari</h2></div></div><form className="admin-card-form" onSubmit={addCard}><Input placeholder="Bank nomi" value={form.bankName} onChange={(e) => setForm({ ...form, bankName: e.target.value })} /><Input placeholder="8600 1234 5678 9012" value={form.cardNumber} onChange={(e) => setForm({ ...form, cardNumber: e.target.value })} /><Input placeholder="Karta egasi" value={form.holderName} onChange={(e) => setForm({ ...form, holderName: e.target.value })} /><Input placeholder="Narx (ixtiyoriy)" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /><Button htmlType="submit" type="primary" icon={<PlusOutlined />} loading={busy}>Karta qo'shish</Button></form><div className="admin-card-list">{methods.map((method) => <div className="admin-card-row" key={method.id}><div><strong>{method.bankName || "Karta"}</strong><span>{method.cardNumber} · {method.holderName}</span></div><button type="button" onClick={() => removePaymentMethod(method.id).then(reload)}><DeleteOutlined /></button></div>)}</div></div><div className="admin-surface"><div className="admin-surface-head"><div><span className="admin-kicker">Tekshiruv</span><h2>To'lov so'rovlari</h2></div><span className="admin-count">{requests.length} ta</span></div><div className="admin-payment-list">{requests.length === 0 ? <div className="admin-empty">Hali to'lov so'rovi yo'q.</div> : requests.map((payment) => <article className="admin-payment-row" key={payment.id}><div><strong>{payment.username || payment.userId}</strong><span>{payment.createdAt ? new Date(payment.createdAt).toLocaleString("uz-UZ") : ""}</span><a href={payment.receiptUrl} target="_blank" rel="noreferrer">Chek rasmini ko'rish</a></div><b className={`payment-pill ${payment.status}`}>{payment.status}</b>{payment.status === "pending" && <div className="payment-actions"><button type="button" className="approve" onClick={() => decide(payment, "approved")}><CheckOutlined /> Tasdiqlash</button><button type="button" className="reject" onClick={() => decide(payment, "rejected")}><CloseOutlined /> Bekor qilish</button></div>}</article>)}</div></div></div></section>;
};
export default AdminPayments;
