import React, { createContext, useContext, useState } from "react";

const translations = {
  uz: {
    home: "Asosiy",
    transactions: "Kirim-chiqim",
    reports: "Hisobot",
    settings: "Sozlamalar",
    notifications: "Bildirishnomalar",
    admin: "Admin",
    profile: "Profil",
    language: "Til",
    pro: "Moliyam Pro",
    upgrade: "Pro tarifga o'tish",
    save: "Saqlash",
    activity: "Faoliyat",
    today: "Bugungi tranzaksiyalar",
    all: "Barcha tranzaksiyalar",
    income: "Kirim",
    expense: "Chiqim",
    add: "Tranzaksiya qo'shish",
    loading: "Yuklanmoqda...",
    noData: "Hali ma'lumot yo'q",
    proTitle: "Moliyangizni keyingi darajaga olib chiqing.",
    proLead: "Ko'proq tushuncha, yaxshiroq reja, xotirjam kelajak.",
    proSmart: "Moliyangizni yanada aqlli boshqaring.",
    paymentTitle: "Moliyam Pro tarifiga o'tish",
    paymentHelp: "Admin ko'rsatgan kartaga to'lov qiling va chek rasmini yuboring.",
    chooseReceipt: "Chek rasmini tanlash",
    sendPayment: "To'lovni yuborish",
    dashboardCenter: "Moliyaviy nazorat markazi",
    hello: "Salom, {name}!",
    dashboardSubtitle: "Bugungi qarorlaringiz ertangi xotirjamlikni yaratadi.",
    yourBalance: "Sizning hisobingiz",
    allTime: "Barcha vaqt bo'yicha",
    totalIncome: "Jami kirim",
    totalExpense: "Jami chiqim",
    monthlyView: "Oylik ko'rinish",
    monthlyDynamic: "{month} dinamikasi",
    incomeLegend: "Kirim",
    expenseLegend: "Chiqim",
    monthIncome: "Bu oy kirim",
    monthExpense: "Bu oy chiqim",
    insight: "Siz uchun",
    financialHabit: "Moliyaviy odat",
    detailAnalysis: "Batafsil tahliz",
    noTransactionsToday: "Bugun hali tranzaksiya yo'q. Birinchi yozuvingizni qo'shing.",
    transactionDefault: "Nomsiz tranzaksiya",
    loginRequiredDashboard: "Dashboard uchun login qiling",
    neutralReport: "Hisobotni ko'rish uchun login qiling",
    financialAnalysis: "Moliyaviy tahlil",
    reportSubtitle: "Daromad va xarajatlaringizni bir joyda kuzating.",
    planned: "Rejalashtirilgan",
    expenseRate: "Sarf",
    searchPlaceholder: "Izoh yoki kategoriya bo'yicha qidirish",
    exportCSV: "CSV",
    exportPDF: "PDF",
    relationship: "Nisbat",
    incomeAndExpense: "Kirim va chiqim",
    selectReceipt: "Chek tasdig'ini tanlang",
    login: "Kirish",
    register: "Hisob ochish",
    logout: "Chiqish",
    reminders: "Eslatmalar",
    remindersText: "Rejalashtirilgan xarajatlar haqida xabar oling",
    enableReminders: "Eslatmalar yoqildi",
    reminderPermissionDenied: "Bildirishnomaga ruxsat berilmadi",
    appLockTitle: "Ilova qulflangan",
    appLockSecureArea: "shaxsiy moliyaviy hudud",
    appLockFooter: "Ma'lumotlaringiz himoyalangan",
    appLockText: "Ilovani ochish uchun 4 xonali PIN-kodingizni kiriting.",
    appLockWait: "Ko'p urinish bajarildi. Qayta urinib ko'rish: {time}",
    appLockPlaceholder: "4 xonali PIN",
    appLockDeleteDigit: "Oxirgi raqamni o'chirish",
    appLockUnlock: "Ochish",
    appLockAttempts: "Xato urinishlar: {count}/3",
    appLockWrongPin: "PIN-kod noto'g'ri.",
    appLockBlocked: "3 marta xato kiritildi. Ilova 10 daqiqaga bloklandi.",
    appLockSettingsTitle: "Ilova PIN-kodi",
    appLockEnabled: "PIN-kod yoqilgan",
    appLockDisabled: "Ilovani PIN bilan himoyalang",
    appLockPinPlaceholder: "Yangi 4 xonali PIN",
    appLockPinConfirmPlaceholder: "PIN-kodni tasdiqlang",
    appLockPinSave: "PIN-kodni saqlash",
    appLockPinRemove: "O'chirish",
    appLockPinMismatch: "PIN-kod 4 xonali bo'lishi va bir xil kiritilishi kerak.",
    appLockPinSaved: "Ilova PIN-kodi saqlandi.",
    appLockPinRemoved: "Ilova PIN-kodi o'chirildi.",
    notificationPermissionTitle: "Bildirishnomalarni yoqish",
    notificationPermissionText: "Rejalashtirilgan xarajatlar, to'lovlar va muhim xabarlarni vaqtida olish uchun notification ruxsatini bering.",
    notificationPermissionLater: "Keyinroq",
    notificationPermissionAllow: "Ruxsat berish",
    changePhoto: "Rasmni almashtirish",
    chooseLanguage: "Ilova tilini tanlang",
    profileName: "Ism",
    profilePhone: "Telefon",
    profileAddress: "Manzil",
    profileEmail: "Email",
    profileSummary: "Shaxsiy moliya boshqaruvi",
    editProfile: "Profilni o'zgartirish",
    profileSummaryTitle: "Shaxsiy ma'lumotlar",
    profileSummaryHint: "Hisobingiz haqidagi asosiy ma'lumotlar",
    profilePlaceholder: "Ismingizni kiriting",
    phonePlaceholder: "+998 90 123 45 67",
    addressPlaceholder: "Manzilingizni kiriting",
    emailPlaceholder: "Emailingizni kiriting",
    userProfileTitle: "Profil",
    loginWelcome: "Xush kelibsiz",
    loginTitle: "Hisobingizga kiring",
    loginLead: "Moliyaviy kundaligingiz sizni kutmoqda.",
    emailOrLogin: "Email yoki login",
    password: "Parol",
    passwordPlaceholder: "Parolingizni kiriting",
    forgotPassword: "Parolni unutdingizmi?",
    newUser: "Yangi foydalanuvchimisiz?",
    createAccount: "Hisob ochish",
    welcomeMessage: "Har bir so'm o'z o'rnida.",
    pricingHero: "Moliyaviy kundalik",
    authOrbit: "nazorat sizning qo'lingizda",
    registerWelcome: "Qo'shilish",
    registerTitle: "O'z hisobingizni yarating",
    registerLead: "Barcha moliyaviy rejalaringiz bir joyda.",
    username: "Foydalanuvchi nomi",
    emailAddress: "Email manzil",
    usernamePlaceholder: "username",
    emailPlaceholderRegister: "sizning@emailingiz.uz",
    passwordHint: "Kamida 6 ta belgi",
    existingAccount: "Hisobingiz bormi?",
    userList: "Foydalanuvchilar",
    overview: "Umumiy ko'rinish",
    sections: "Bo'limlar",
    broadcast: "Broadcast",
    adminPayments: "Pro to'lovlar",
    managePayments: "To'lovlar boshqaruvi",
    paymentLoadError: "Ma'lumotlarni yuklab bo'lmadi",
    cardNumberRequired: "Karta raqamini kiriting",
    cardAdded: "Karta qo'shildi",
    cardNotSaved: "Karta saqlanmadi",
    cardApproved: "Pro tasdiqlandi",
    cardRejected: "To'lov bekor qilindi",
    paymentActionFailed: "Amalni bajarib bo'lmadi",
    bankNameLabel: "Bank nomi",
    cardNumberLabel: "8600 1234 5678 9012",
    holderNameLabel: "Karta egasi",
    priceOptionalLabel: "Narx (ixtiyoriy)",
    addCardButton: "Karta qo'shish",
    paymentCardDefault: "Karta",
    approveLabel: "Tasdiqlash",
    rejectLabel: "Rad etish",
    reviewLabel: "Tekshiruv",
    paymentReceive: "Qabul qilish",
    paymentRequestPending: "Tekshirilmoqda",
    paymentCount: "{count} ta",
    noPaymentRequests: "Hali to'lov so'rovi yo'q.",
    sectionAdded: "Yangi bo'lim qo'shildi",
    sectionSaveFailed: "Bo'limni saqlab bo'lmadi",
    sectionDeleteFailed: "Bo'limni o'chirib bo'lmadi",
    notificationTitleRequired: "Sarlavha va xabar matnini kiriting",
    notificationQueued: "Xabar Firebase navbatiga qo'shildi ({count} ta qabul qiluvchi)",
    notificationDeliveryFailed: "Xabarni yuborishda serverga ulanib bo'lmadi",
    exampleNotification: "Masalan: Yangi imkoniyat",
    removeSectionAria: "{name} bo'limini o'chirish",
    foodCategory: "Oziq-ovqat",
    transportCategory: "Transport",
    homeCategory: "Uy-joy",
    healthCategory: "Salomatlik",
    proWorkspace: "Pro markaz",
    advancedAnalysis: "Kengaytirilgan tahlil",
    healthScore: "Moliyaviy salomatlik",
    healthy: "Barqaror holat",
    needsAttention: "E'tibor kerak",
    savingsRate: "Jamg'arish darajasi",
    plannedItems: "Rejalashtirilgan",
    topCategory: "Eng katta xarajat",
    aiAdvisor: "Moliyam AI maslahatchi",
    proInsightEmpty: "Tahlil uchun hali yetarli tranzaksiya yo'q. Bir nechta yozuv qo'shing.",
    proInsightPositive: "Ajoyib. Siz bu oy daromadingizning {rate}% qismini saqlab qolyapsiz.",
    proInsightNegative: "Bu oy xarajatlaringiz {amount} so'm bo'ldi. Keyingi xarajatlarni rejalashtirib ko'ring.",
    budgetGoal: "Oylik budjet maqsadi",
    budgetGoalEmpty: "Xarajat limitingizni belgilang va sarfni kuzating.",
    budgetGoalPlaceholder: "Masalan: 5000000",
    saveGoal: "Maqsadni saqlash",
    budgetWarning: "Diqqat: budjet limitingizning 80% dan ko'pi ishlatildi.",
    categoryBreakdown: "Xarajatlar tarkibi",
    topFive: "Top 5 kategoriya",
    noCategoryData: "Kategoriya tahlili uchun ma'lumot yetarli emas.",
    monthlyComparison: "Oylik taqqoslash",
    expenseTrend: "Oldingi oyga nisbatan",
    expenseIncreased: "Bu oy xarajatlar oshgan.",
    expenseDecreased: "Bu oy xarajatlar kamaygan yoki o'zgarmagan.",
    educationCategory: "Ta'lim",
    entertainmentCategory: "Ko'ngilochar",
    salaryCategory: "Ish haqi",
    generalCategory: "Umumiy",
    notificationsIntro: "Siz uchun muhim yangiliklar va to'lov holatlari.",
    newNotificationsHere: "Yangi bildirishnomalar shu yerda ko'rinadi.",
    notificationLoadError: "Bildirishnomalarni yuklab bo'lmadi.",
    transactionPrompt: "Daromad yoki xarajatni kiriting.",
    exampleExpenseNote: "Masalan: Oylik xaridlar",
    loginRequired: "Avval tizimga kiring (login).",
    invalidAmount: "Summani to'g'ri kiriting!",
    invalidType: "Turi noto'g'ri!",
    saveSuccess: "Saqlandi!",
    saveFailed: "Xatolik yuz berdi!",
    errorPrefix: "Xatolik:",
    activatePro: "Pro tarifni faollashtiring",
    defaultBankCard: "Moliyam karta",
    paymentSummaryNote: "To'lov summasi admin belgilagan karta bo'yicha tekshiriladi.",
    uploadReceiptHint: "Bank ilovasidan to'lov chekini screenshot qiling va shu yerga yuklang.",
    removeCard: "Kartani o'chirish",
    viewReceipt: "Chek rasmini ko'rish",
    accountAccessDenied: "Kirish cheklangan",
    adminOnlyMessage: "Bu bo'lim faqat administratorlar uchun.",
    dashboardPanel: "Boshqaruv paneli",
    teamLabel: "Jamoa",
    userLabel: "Foydalanuvchi",
    statusLabel: "Holat",
    quickAction: "Tezkor amal",
    sendTeamMessage: "Jamoangizga xabar yuboring",
    teamMessageText: "Yangilik, eslatma yoki muhim e'lonni barcha foydalanuvchilarga yuboring.",
    categorySection: "Tasnif",
    categoryHelp: "Foydalanuvchilar xarajatlarini tartibli yozishi uchun bo'limlar yarating.",
    monitorPlatform: "Platforma nazorat ostida",
    adminRole: "Administrator",
    paymentAcceptedNotice: "Pro tarif faollashdi",
    paymentAcceptedBody: "Tabriklaymiz! Siz Moliyam Pro tarifiga o'tdingiz.",
    paymentRejectedNotice: "To'lov bekor qilindi",
    paymentRejectedBody: "To'lovingiz tasdiqlanmadi. Iltimos, chek rasmini tekshirib qayta yuboring.",
    todayDate: "Bugun, {date}",
    totalUsers: "Jami foydalanuvchilar",
    activeProfiles: "Faol profillar",
    transactionsCount: "Tranzaksiyalar",
    allRecords: "Barcha yozuvlar",
    totalExpenses: "Jami chiqim",
    plannedExpenses: "Rejalashtirilgan",
    upcomingExpense: "Kutilayotgan xarajat",
    allUsers: "Barchasi",
    mostActive: "Eng faol",
    userListTitle: "Foydalanuvchilar ro'yxati",
    profiles: "profil",
    activeStatus: "Faol",
    transactionCountLabel: "ta tranzaksiya",
    categoriesTitle: "Harajat bo'limlari",
    newSectionName: "Yangi bo'lim nomi",
    addSection: "Qo'shish",
    viewMode: "Ko'rinish",
    categories: "Kategoriyalar",
    newNotification: "Yangi bildirishnoma",
    sendTo: "Kimga yuboriladi",
    allUsersOption: "Barcha foydalanuvchilar",
    messageText: "Xabar matni",
    messagePlaceholder: "Xabaringizni shu yerga yozing...",
    sendNotification: "Bildirishnoma yuborish",
    archive: "Arxiv",
    latestMessages: "So'nggi xabarlar",
    noMessagesSent: "Hali xabar yuborilmagan",
    pushCount: "{count} ta push",
    addTransactionTitle: "Kirim/Chiqim kiritish",
    loginToAccess: "Bu bo'limdan foydalanish uchun avval login qiling.",
    newEntry: "Yangi yozuv",
    transactionType: "Tranzaksiya turi",
    amount: "Summa",
    category: "Kategoriya",
    dueDate: "Qachon sarflanadi?",
    optional: "(ixtiyoriy)",
    reminderToggle: "Eslatma yoqilsin",
    reminderHint: "1 kun oldin va belgilangan kuni har 2 soatda",
    note: "Izoh",
    saveProgress: "Saqlanmoqda...",
    receivingPayment: "To'lovni yuborish",
    paymentStatus: "To'lov holati",
    noPaymentInfo: "Admin hali karta qo'shmagan.",
    paymentDetails: "To'lov uchun karta",
    paymentProof: "To'lov tasdig'i",
    confirmPayment: "To'lovni tasdiqlash",
    verifyPending: "Tekshirilmoqda",
    approved: "Pro faollashdi",
    rejected: "To'lov bekor qilindi",
    waitingAdmin: "Admin tasdig'ini kuting.",
    uploadReceipt: "Rasm tanlash",
    cardAddSuccess: "Karta qo'shildi",
    cardSaveError: "Karta saqlanmadi",
    cardNumber: "Karta raqami",
    holderName: "Karta egasi",
    priceOptional: "Narx (ixtiyoriy)",
    checkPaymentRequests: "To'lov so'rovlari",
    backToAdmin: "Admin panelga qaytish",
    backToPro: "Pro tarifga qaytish",
    activeSubscription: "Faol obuna",
    premiumPlan: "Premium reja",
    proActive: "Pro faol",
    proMonthly: "Moliyam Pro Monthly",
    subscriptionActive: "Obuna faol",
    waitUntil: "{date} gacha",
    targetBlank: "Ko'rish →",
    feature1: "Kengaytirilgan tahlil",
    feature2: "Budjetlar va moliyaviy maqsadlar",
    feature3: "AI moliyaviy yordamchi",
    feature4: "Aqlli bildirishnomalar",
    feature5: "Qarzlar va takroriy tranzaksiyalar",
    feature6: "Professional hisobotlar",
    feature7: "Oilaviy moliya",
    feature8: "Moliyaviy salomatlik ko'rsatkichi",
    activePlan: "Faol reja",
    statusUnknown: "Obuna holatini tekshirib bo'lmadi.",
    paymentCardRequired: "Karta va chek rasmini tanlang",
    paymentSubmitted: "To'lov so'rovi yuborildi",
    paymentFailed: "To'lovni yuborib bo'lmadi",
    submitting: "Yuborilmoqda...",
    cardTransferRequired: "Karta o'tkazmasi rasmi va faol karta kerak",
    paymentReceiptSent: "To'lov rasmi yuborildi. Admin tekshiradi.",
    adminReview: "Admin ko'rsatgan kartaga to'lov qiling va chek rasmini yuboring.",
    chartFilter: "Barcha",
    chartIncome: "Kirim",
    chartExpense: "Chiqim",
    allProfiles: "Barcha profil",
    createdAt: "Yaratildi",
    notFound: "Topilmadi",
    pleaseWait: "Iltimos, kuting...",
    monthlyCurrency: "so'm"
  },
  ru: {
    home: "Главная",
    transactions: "Доходы-расходы",
    reports: "Отчёты",
    settings: "Настройки",
    notifications: "Уведомления",
    admin: "Админ",
    profile: "Профиль",
    language: "Язык",
    pro: "Moliyam Pro",
    upgrade: "Перейти на Pro",
    save: "Сохранить",
    activity: "Активность",
    today: "Сегодняшние операции",
    all: "Все операции",
    income: "Доход",
    expense: "Расход",
    add: "Добавить операцию",
    loading: "Загрузка...",
    noData: "Пока нет данных",
    proTitle: "Выведите свои финансы на новый уровень.",
    proLead: "Больше понимания, лучший план, спокойное будущее.",
    proSmart: "Управляйте финансами умнее.",
    dashboardCenter: "Центр финансового контроля",
    hello: "Привет, {name}!",
    dashboardSubtitle: "Сегодняшние решения формируют спокойствие завтра.",
    yourBalance: "Ваш баланс",
    allTime: "За всё время",
    totalIncome: "Общий доход",
    totalExpense: "Общий расход",
    monthlyView: "Ежемесячный обзор",
    monthlyDynamic: "Динамика {month}",
    incomeLegend: "Доход",
    expenseLegend: "Расход",
    monthIncome: "Доход за этот месяц",
    monthExpense: "Расход за этот месяц",
    insight: "Для вас",
    financialHabit: "Финансовая привычка",
    detailAnalysis: "Подробнее",
    noTransactionsToday: "Сегодня ещё нет операций. Добавьте первую запись.",
    transactionDefault: "Без названия",
    loginRequiredDashboard: "Войдите, чтобы открыть панель",
    neutralReport: "Войдите, чтобы просматривать отчёт",
    financialAnalysis: "Финансовый анализ",
    reportSubtitle: "Следите за доходами и расходами в одном месте.",
    planned: "Запланировано",
    expenseRate: "Расход",
    searchPlaceholder: "Поиск по описанию или категории",
    exportCSV: "CSV",
    exportPDF: "PDF",
    relationship: "Соотношение",
    incomeAndExpense: "Доход и расход",
    login: "Войти",
    register: "Создать аккаунт",
    logout: "Выйти",
    reminders: "Напоминания",
    remindersText: "Получайте уведомления о запланированных расходах",
    enableReminders: "Напоминания включены",
    reminderPermissionDenied: "Уведомления не разрешены",
    appLockTitle: "Приложение заблокировано",
    appLockSecureArea: "личная финансовая зона",
    appLockFooter: "Ваши данные защищены",
    appLockText: "Введите 4-значный PIN-код, чтобы открыть приложение.",
    appLockWait: "Слишком много попыток. Повторить через: {time}",
    appLockPlaceholder: "4-значный PIN",
    appLockDeleteDigit: "Удалить последнюю цифру",
    appLockUnlock: "Открыть",
    appLockAttempts: "Ошибок: {count}/3",
    appLockWrongPin: "Неверный PIN-код.",
    appLockBlocked: "3 ошибки. Приложение заблокировано на 10 минут.",
    appLockSettingsTitle: "PIN-код приложения",
    appLockEnabled: "PIN-код включён",
    appLockDisabled: "Защитите приложение PIN-кодом",
    appLockPinPlaceholder: "Новый 4-значный PIN",
    appLockPinConfirmPlaceholder: "Подтвердите PIN-код",
    appLockPinSave: "Сохранить PIN",
    appLockPinRemove: "Удалить",
    appLockPinMismatch: "PIN должен состоять из 4 одинаково введённых цифр.",
    appLockPinSaved: "PIN-код приложения сохранён.",
    appLockPinRemoved: "PIN-код приложения удалён.",
    notificationPermissionTitle: "Включить уведомления",
    notificationPermissionText: "Разрешите уведомления, чтобы вовремя получать напоминания о расходах, оплатах и важные сообщения.",
    notificationPermissionLater: "Позже",
    notificationPermissionAllow: "Разрешить",
    changePhoto: "Сменить фото",
    chooseLanguage: "Выберите язык приложения",
    profileName: "Имя",
    profilePhone: "Телефон",
    profileAddress: "Адрес",
    profileEmail: "Email",
    profileSummary: "Личное управление финансами",
    editProfile: "Изменить профиль",
    profileSummaryTitle: "Личные данные",
    profileSummaryHint: "Основная информация о вашем аккаунте",
    profilePlaceholder: "Введите имя",
    phonePlaceholder: "+998 90 123 45 67",
    addressPlaceholder: "Введите адрес",
    emailPlaceholder: "Введите email",
    userProfileTitle: "Профиль",
    loginWelcome: "Добро пожаловать",
    loginTitle: "Войдите в аккаунт",
    loginLead: "Ваш финансовый дневник ждёт вас.",
    emailOrLogin: "Email или логин",
    password: "Пароль",
    passwordPlaceholder: "Введите пароль",
    forgotPassword: "Забыли пароль?",
    newUser: "Новый пользователь?",
    createAccount: "Создать аккаунт",
    welcomeMessage: "Каждая копейка на своем месте.",
    pricingHero: "Финансовый дневник",
    authOrbit: "контроль в ваших руках",
    registerWelcome: "Присоединиться",
    registerTitle: "Создайте аккаунт",
    registerLead: "Все ваши финансовые планы в одном месте.",
    username: "Имя пользователя",
    emailAddress: "Email адрес",
    usernamePlaceholder: "username",
    emailPlaceholderRegister: "your@email.com",
    passwordHint: "Минимум 6 символов",
    existingAccount: "Уже есть аккаунт?",
    userList: "Пользователи",
    overview: "Обзор",
    sections: "Категории",
    broadcast: "Трансляция",
    adminPayments: "Платежи Pro",
    managePayments: "Управление платежами",
    paymentLoadError: "Не удалось загрузить данные",
    cardNumberRequired: "Введите номер карты",
    cardAdded: "Карта добавлена",
    cardNotSaved: "Карта не сохранена",
    cardApproved: "Pro подтвержден",
    cardRejected: "Платёж отклонён",
    paymentActionFailed: "Не удалось выполнить действие",
    bankNameLabel: "Название банка",
    cardNumberLabel: "8600 1234 5678 9012",
    holderNameLabel: "Владелец карты",
    priceOptionalLabel: "Цена (необязательно)",
    addCardButton: "Добавить карту",
    paymentCardDefault: "Карта",
    approveLabel: "Подтвердить",
    rejectLabel: "Отклонить",
    reviewLabel: "Проверка",
    paymentReceive: "Принять",
    paymentRequestPending: "Проверяется",
    paymentCount: "{count} шт",
    noPaymentRequests: "Пока нет запросов на оплату.",
    sectionAdded: "Новая категория добавлена",
    sectionSaveFailed: "Не удалось сохранить категорию",
    sectionDeleteFailed: "Не удалось удалить категорию",
    notificationTitleRequired: "Введите заголовок и текст сообщения",
    notificationQueued: "Сообщение добавлено в очередь Firebase ({count} получателей)",
    notificationDeliveryFailed: "Не удалось подключиться к серверу при отправке сообщения",
    exampleNotification: "Например: Новая возможность",
    removeSectionAria: "Удалить категорию {name}",
    foodCategory: "Еда",
    transportCategory: "Транспорт",
    homeCategory: "Дом",
    healthCategory: "Здоровье",
    proWorkspace: "Центр Pro",
    advancedAnalysis: "Расширенный анализ",
    healthScore: "Финансовое здоровье",
    healthy: "Стабильное состояние",
    needsAttention: "Требует внимания",
    savingsRate: "Норма сбережений",
    plannedItems: "Запланировано",
    topCategory: "Самый большой расход",
    aiAdvisor: "AI-советник Moliyam",
    proInsightEmpty: "Пока недостаточно операций для анализа. Добавьте несколько записей.",
    proInsightPositive: "Отлично. В этом месяце вы сохраняете {rate}% дохода.",
    proInsightNegative: "В этом месяце расходы составили {amount} сум. Попробуйте планировать следующие траты.",
    budgetGoal: "Месячный бюджет",
    budgetGoalEmpty: "Установите лимит и следите за расходами.",
    budgetGoalPlaceholder: "Например: 5000000",
    saveGoal: "Сохранить цель",
    budgetWarning: "Внимание: использовано более 80% бюджета.",
    categoryBreakdown: "Структура расходов",
    topFive: "Топ-5 категорий",
    noCategoryData: "Недостаточно данных для анализа категорий.",
    monthlyComparison: "Сравнение месяцев",
    expenseTrend: "По сравнению с прошлым месяцем",
    expenseIncreased: "В этом месяце расходы выросли.",
    expenseDecreased: "В этом месяце расходы снизились или не изменились.",
    educationCategory: "Образование",
    entertainmentCategory: "Развлечения",
    salaryCategory: "Зарплата",
    generalCategory: "Общее",
    notificationsIntro: "Важные новости и статусы оплат для вас.",
    newNotificationsHere: "Новые уведомления появятся здесь.",
    notificationLoadError: "Не удалось загрузить уведомления.",
    transactionPrompt: "Введите доход или расход.",
    exampleExpenseNote: "Например: Ежемесячные покупки",
    loginRequired: "Сначала войдите в систему.",
    invalidAmount: "Введите корректную сумму!",
    invalidType: "Неверный тип!",
    saveSuccess: "Сохранено!",
    saveFailed: "Произошла ошибка!",
    errorPrefix: "Ошибка:",
    activatePro: "Активировать Pro",
    defaultBankCard: "Карта Moliyam",
    paymentSummaryNote: "Сумма оплаты проверяется по карте администратора.",
    uploadReceiptHint: "Сделайте скриншот чека оплаты и загрузите его сюда.",
    noPaymentInfo: "Администратор пока не добавил карту.",
    removeCard: "Удалить карту",
    viewReceipt: "Открыть чек",
    accountAccessDenied: "Доступ ограничен",
    adminOnlyMessage: "Этот раздел только для администраторов.",
    dashboardPanel: "Панель управления",
    teamLabel: "Команда",
    userLabel: "Пользователь",
    statusLabel: "Статус",
    quickAction: "Быстрое действие",
    sendTeamMessage: "Отправить сообщение команде",
    teamMessageText: "Рассылайте новости, напоминания и важные объявления всем пользователям.",
    categorySection: "Классификация",
    categoryHelp: "Создавайте категории, чтобы пользователи вели расходы аккуратно.",
    monitorPlatform: "Платформа под контролем",
    adminRole: "Администратор",
    paymentAcceptedNotice: "Pro тариф активирован",
    paymentAcceptedBody: "Поздравляем! Вы перешли на Moliyam Pro.",
    paymentRejectedNotice: "Платёж отклонён",
    paymentRejectedBody: "Ваш платёж не подтверждён. Проверьте чек и отправьте заново.",
    todayDate: "Сегодня, {date}",
    totalUsers: "Всего пользователей",
    activeProfiles: "Активные профили",
    transactionsCount: "Транзакции",
    allRecords: "Все записи",
    totalExpenses: "Общий расход",
    plannedExpenses: "Запланировано",
    upcomingExpense: "Ожидаемые расходы",
    allUsers: "Все",
    mostActive: "Самые активные",
    userListTitle: "Список пользователей",
    profiles: "профилей",
    activeStatus: "Активен",
    transactionCountLabel: "транзакций",
    categoriesTitle: "Категории расходов",
    newSectionName: "Название новой категории",
    addSection: "Добавить",
    viewMode: "Вид",
    categories: "Категории",
    newNotification: "Новое уведомление",
    sendTo: "Кому отправить",
    allUsersOption: "Все пользователи",
    messageText: "Текст сообщения",
    messagePlaceholder: "Введите сообщение...",
    sendNotification: "Отправить уведомление",
    archive: "Архив",
    latestMessages: "Последние сообщения",
    noMessagesSent: "Уведомления ещё не отправлялись",
    pushCount: "{count} push",
    amount: "Сумма",
    category: "Категория",
    dueDate: "Когда потратить?",
    optional: "(необязательно)",
    saveProgress: "Сохранение...",
    selectReceipt: "Выберите квитанцию",
    addTransactionTitle: "Добавить доход/расход",
    reminderToggle: "Включить напоминание",
    reminderHint: "за 1 день и каждые 2 часа в день оплаты",
    note: "Примечание",
    paymentTitle: "Переход на Moliyam Pro",
    paymentHelp: "Оплатите на карту администратора и отправьте чек.",
    chooseReceipt: "Выбрать чек",
    sendPayment: "Отправить оплату",
    monthlyCurrency: "сум",
    chartFilter: "Все",
    chartIncome: "Доход",
    chartExpense: "Расход"
  },
  en: {
    home: "Home",
    transactions: "Income-expenses",
    reports: "Reports",
    settings: "Settings",
    notifications: "Notifications",
    admin: "Admin",
    profile: "Profile",
    language: "Language",
    pro: "Moliyam Pro",
    upgrade: "Upgrade to Pro",
    save: "Save",
    activity: "Activity",
    today: "Today's transactions",
    all: "All transactions",
    income: "Income",
    expense: "Expense",
    add: "Add transaction",
    loading: "Loading...",
    noData: "No data yet",
    proTitle: "Take your finances to the next level.",
    proLead: "More insight, a better plan, a calmer future.",
    proSmart: "Manage your money smarter.",
    paymentTitle: "Upgrade to Moliyam Pro",
    paymentHelp: "Pay to the administrator's card and upload your receipt.",
    chooseReceipt: "Choose receipt",
    sendPayment: "Send payment",
    dashboardCenter: "Financial control center",
    hello: "Hello, {name}!",
    dashboardSubtitle: "Today's decisions create tomorrow's peace of mind.",
    yourBalance: "Your balance",
    allTime: "All time",
    totalIncome: "Total income",
    totalExpense: "Total expense",
    monthlyView: "Monthly view",
    monthlyDynamic: "{month} overview",
    incomeLegend: "Income",
    expenseLegend: "Expense",
    monthIncome: "This month income",
    monthExpense: "This month expense",
    insight: "For you",
    financialHabit: "Financial habit",
    detailAnalysis: "Detailed analysis",
    noTransactionsToday: "No transactions today yet. Add your first entry.",
    transactionDefault: "Untitled transaction",
    loginRequiredDashboard: "Please log in to view dashboard",
    neutralReport: "Please log in to view report",
    financialAnalysis: "Financial analysis",
    reportSubtitle: "Track your income and expenses in one place.",
    planned: "Planned",
    expenseRate: "Expense",
    searchPlaceholder: "Search by note or category",
    exportCSV: "CSV",
    exportPDF: "PDF",
    relationship: "Ratio",
    incomeAndExpense: "Income and expense",
    login: "Log in",
    register: "Create account",
    logout: "Log out",
    reminders: "Reminders",
    remindersText: "Get notifications about planned expenses",
    enableReminders: "Reminders enabled",
    reminderPermissionDenied: "Notification permission denied",
    appLockTitle: "App locked",
    appLockSecureArea: "your private finance space",
    appLockFooter: "Your data is protected",
    appLockText: "Enter your 4-digit PIN to open the app.",
    appLockWait: "Too many attempts. Try again in: {time}",
    appLockPlaceholder: "4-digit PIN",
    appLockDeleteDigit: "Delete last digit",
    appLockUnlock: "Unlock",
    appLockAttempts: "Failed attempts: {count}/3",
    appLockWrongPin: "Incorrect PIN.",
    appLockBlocked: "Three failed attempts. The app is locked for 10 minutes.",
    appLockSettingsTitle: "App PIN",
    appLockEnabled: "PIN enabled",
    appLockDisabled: "Protect the app with a PIN",
    appLockPinPlaceholder: "New 4-digit PIN",
    appLockPinConfirmPlaceholder: "Confirm PIN",
    appLockPinSave: "Save PIN",
    appLockPinRemove: "Remove",
    appLockPinMismatch: "The PIN must contain 4 matching digits.",
    appLockPinSaved: "App PIN saved.",
    appLockPinRemoved: "App PIN removed.",
    notificationPermissionTitle: "Enable notifications",
    notificationPermissionText: "Allow notifications to receive expense reminders, payment updates, and important messages on time.",
    notificationPermissionLater: "Later",
    notificationPermissionAllow: "Allow",
    changePhoto: "Change photo",
    chooseLanguage: "Choose app language",
    profileName: "Name",
    profilePhone: "Phone",
    profileAddress: "Address",
    profileEmail: "Email",
    profileSummary: "Personal finance management",
    editProfile: "Edit profile",
    profileSummaryTitle: "Personal details",
    profileSummaryHint: "Key information about your account",
    profilePlaceholder: "Enter your name",
    phonePlaceholder: "+998 90 123 45 67",
    addressPlaceholder: "Enter your address",
    emailPlaceholder: "Enter your email",
    userProfileTitle: "Profile",
    loginWelcome: "Welcome",
    loginTitle: "Sign in to your account",
    loginLead: "Your financial journal is waiting for you.",
    emailOrLogin: "Email or username",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    forgotPassword: "Forgot password?",
    newUser: "New user?",
    createAccount: "Create account",
    welcomeMessage: "Every penny in the right place.",
    pricingHero: "Financial daily",
    authOrbit: "control in your hands",
    registerWelcome: "Join",
    registerTitle: "Create your account",
    registerLead: "All your financial plans in one place.",
    username: "Username",
    emailAddress: "Email address",
    usernamePlaceholder: "username",
    emailPlaceholderRegister: "your@email.com",
    passwordHint: "Minimum 6 characters",
    existingAccount: "Already have an account?",
    userList: "Users",
    overview: "Overview",
    sections: "Sections",
    broadcast: "Broadcast",
    adminPayments: "Pro payments",
    managePayments: "Payment management",
    educationCategory: "Education",
    entertainmentCategory: "Entertainment",
    salaryCategory: "Salary",
    generalCategory: "General",
    notificationsIntro: "Important updates and payment status for you.",
    newNotificationsHere: "New notifications will appear here.",
    notificationLoadError: "Failed to load notifications.",
    transactionPrompt: "Enter an income or expense.",
    exampleExpenseNote: "e.g. Monthly purchases",
    loginRequired: "Please log in first.",
    invalidAmount: "Please enter a valid amount!",
    invalidType: "Invalid type!",
    saveSuccess: "Saved!",
    saveFailed: "An error occurred!",
    errorPrefix: "Error:",
    activatePro: "Activate Pro",
    defaultBankCard: "Moliyam card",
    paymentSummaryNote: "The payment amount is checked against the admin card.",
    uploadReceiptHint: "Take a screenshot of your payment receipt and upload it here.",
    noPaymentInfo: "The admin has not added any card yet.",
    removeCard: "Remove card",
    viewReceipt: "View receipt",
    proWorkspace: "Pro center",
    advancedAnalysis: "Advanced analysis",
    healthScore: "Financial health",
    healthy: "Healthy",
    needsAttention: "Needs attention",
    savingsRate: "Savings rate",
    plannedItems: "Planned items",
    topCategory: "Largest expense",
    aiAdvisor: "Moliyam AI advisor",
    proInsightEmpty: "There are not enough transactions to analyze yet. Add a few entries.",
    proInsightPositive: "Great. You are saving {rate}% of your income this month.",
    proInsightNegative: "Your expenses reached {amount} sum this month. Try planning your next expenses.",
    budgetGoal: "Monthly budget goal",
    budgetGoalEmpty: "Set a limit and track your spending.",
    budgetGoalPlaceholder: "e.g. 5000000",
    saveGoal: "Save goal",
    budgetWarning: "Attention: more than 80% of your budget is used.",
    categoryBreakdown: "Spending breakdown",
    topFive: "Top 5 categories",
    noCategoryData: "Not enough data for category analysis.",
    monthlyComparison: "Monthly comparison",
    expenseTrend: "Compared with last month",
    expenseIncreased: "Your spending increased this month.",
    expenseDecreased: "Your spending decreased or stayed the same this month.",
    accountAccessDenied: "Access denied",
    adminOnlyMessage: "This section is for admins only.",
    todayDate: "Today, {date}",
    totalUsers: "Total users",
    activeProfiles: "Active profiles",
    transactionsCount: "Transactions",
    allRecords: "All records",
    totalExpenses: "Total expense",
    plannedExpenses: "Planned",
    upcomingExpense: "Upcoming expense",
    allUsers: "All",
    mostActive: "Most active",
    userListTitle: "Users list",
    profiles: "profiles",
    activeStatus: "Active",
    transactionCountLabel: "transactions",
    categoriesTitle: "Expense categories",
    newSectionName: "New category name",
    addSection: "Add",
    viewMode: "View",
    categories: "Categories",
    newNotification: "New notification",
    sendTo: "Send to",
    allUsersOption: "All users",
    messageText: "Message text",
    messagePlaceholder: "Write your message here...",
    sendNotification: "Send notification",
    archive: "Archive",
    latestMessages: "Recent messages",
    noMessagesSent: "No messages sent yet",
    pushCount: "{count} pushes",
    amount: "Amount",
    category: "Category",
    dueDate: "When will it be spent?",
    optional: "(optional)",
    saveProgress: "Saving...",
    selectReceipt: "Select receipt",
    addTransactionTitle: "Add income/expense",
    reminderToggle: "Enable reminder",
    reminderHint: "1 day in advance and every 2 hours on the due date",
    note: "Note",
    monthlyCurrency: "sum",
    chartFilter: "All",
    chartIncome: "Income",
    chartExpense: "Expense"
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem("moliyam-language") || "uz";
    } catch {
      return "uz";
    }
  });

  const changeLanguage = (next) => {
    setLanguage(next);
    try {
      localStorage.setItem("moliyam-language", next);
    } catch {
      return;
    }
  };

  const t = (key, params = {}) => {
    const base = translations[language]?.[key] || translations.uz[key] || key;
    return Object.entries(params).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), base);
  };

  return <LanguageContext.Provider value={{ language, changeLanguage, t }}>{children}</LanguageContext.Provider>;
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);
